export const AUDIO_STEMS_QUEUE = 'audio-stems';
export const AUDIO_STEMS_JOB = 'separate';
export const DEFAULT_STEMS_ENGINE_VERSION = '1';
export const DEFAULT_DEMUCS_MODEL = 'htdemucs';

export const STEMS_ERROR_CODE = {
  ALREADY_RUNNING: 'AUDIO_STEM_ALREADY_RUNNING',
  QUEUE_SATURATED: 'AUDIO_STEM_QUEUE_SATURATED',
  REDIS_UNAVAILABLE: 'REDIS_UNAVAILABLE',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  NOT_FOUND: 'AUDIO_STEM_NOT_FOUND',
  PROVIDER_UNSUPPORTED: 'AUDIO_STEM_PROVIDER_UNSUPPORTED',
  AUDIO_DOWNLOAD_FAILED: 'AUDIO_DOWNLOAD_FAILED',
  AUDIO_URL_EXPIRED: 'AUDIO_URL_EXPIRED',
  AUDIO_TOO_LARGE: 'AUDIO_TOO_LARGE',
  AUDIO_TOO_LONG: 'AUDIO_TOO_LONG',
  DEMUCS_FAILED: 'DEMUCS_FAILED',
  DEMUCS_TIMEOUT: 'DEMUCS_TIMEOUT',
  UPLOAD_FAILED: 'AUDIO_STEM_UPLOAD_FAILED',
} as const;
