ALTER TYPE "NotificationType" ADD VALUE 'TEACHING_COURSE_INVITATION';
ALTER TYPE "NotificationType" ADD VALUE 'TEACHING_ENROLLMENT_REQUEST';
ALTER TYPE "NotificationType" ADD VALUE 'TEACHING_ENROLLMENT_UPDATED';
